### ISSUE TITLE
Error in Pre-Processing All Samples from the Vignette

### ISSUE THREAD

**Issue by rmorgan7e** [00berst33/flowFun#3]
When I ran: 

> table <- system.file("extdata", "raw_samples.rds", package = "flowFun")
> table <- readRDS(table)
> 
> prepr_table <- doPreprocessing(table,
                                num_cells = 10000,
                                ld_channel = "BUV496-A", 
                                compensation = comp_mat,
                                transformation_type = "logicle",
                                live_gate = manual_live,
                                nmad = 3.5, 
                                pctg_live = 0.7,
                                pctg_qc = 0.8,
                                save_plots = FALSE,
                                save_fcs = FALSE)

It started and then gave an error on the first file:

[1] "Processing Ab_PHA_Ctrl AWB4.fcs..."
Error in flowCore::read.FCS(file, truncate_max_range = FALSE) : 
  'C:/Users/00ber/OneDrive/Desktop/VPC/human1/Data/Raw/Ab_PHA_Ctrl AWB4.fcs' is not a valid file

**Comment by 00berst33** [comment]
When I was testing this function I'd been using files on my own computer rather than the package's external data, and forgot to change this. This should be resolved now!

**Comment by rmorgan7e** [comment]
I tried it again and got this error:

Error: .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Cairo/libs/Cairo.so, 0x0006): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: <2B39D2DE-4EEA-3AB3-9BC0-0355BE038E52> /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Cairo/libs/Cairo.so
  Reason: tried: '/opt/X11/lib/libXrender.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/X11/lib/libXrender.1.dylib' (no such file), '/opt/X11/lib/libXrender.1.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libXrender.1.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-11.0.18+10/Contents/Home/lib/server/libXrender.1.dylib' (no such file), '/var/folders/sm/q0w2jjzj1wq855zm45k9gsrw0000gn/T/rstudi
In addition: Warning message:
In PeacoQC::RemoveMargins(ff, c("FSC-A", all_channels)) :
  More than 25.77 % is considered as a margin event in file Ab_PHA_Ctrl AWB4.fcs . This should be verified.

**Comment by 00berst33** [comment]
I added the package grDevices to the DESCRIPTION file and switched to using base R functions `pdf()` and `dev.off()` to make the pdf. R is trying to use the package Cairo instead of base R to make the pdf, which I think is because of the dependency missing from DESCRIPTION, but could also be due to the original function I was using, `ggsave()` selecting the wrong graphics device. If this still doesn't fix the issue, could you show me the results of `traceback()`, and also `sessionInfo()`.

**Comment by rmorgan7e** [comment]
It didn't fix the issue :/

When I ran `traceback()` it gave me this:

9: stop(gettextf("%s failed in %s() for '%s', details:\n  call: %s\n  error: %s", 
       hookname, "loadNamespace", pkgname, deparse(conditionCall(res))[1L], 
       conditionMessage(res)), call. = FALSE, domain = NA)
8: runHook(".onLoad", env, package.lib, package)
7: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
6: asNamespace(ns)
5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc, 
       .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
4: loadNamespace(x)
3: withCallingHandlers(expr, warning = function(w) if (inherits(w, 
       classes)) tryInvokeRestart("muffleWarning"))
2: suppressWarnings(flowCut::flowCut(f = ff_l, FileID = make.names(file), 
       Plot = ifelse(save_plots, "Flagged Only", "None"), Directory = file.path("Preprocessing Results", 
           "flowCut"), Verbose = TRUE))
1: doPreprocessing(table, num_cells = 10000, ld_channel = "BUV496-A", 
       compensation = comp_mat, transformation_type = "logicle", 
       live_gate = manual_live, nmad = 3.5, pctg_live = 0.7, pctg_qc = 0.8, 
       save_plots = TRUE, save_fcs = FALSE)

When I ran `sessionInfo()` it gave me this:

R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Vancouver
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flowDensity_1.38.0 flowFun_0.0.0.9000 tidytable_0.11.1   flowCore_2.16.0   

loaded via a namespace (and not attached):
  [1] bitops_1.0-8          deldir_2.0-4          gridExtra_2.3         remotes_2.5.0         rlang_1.1.4          
  [6] magrittr_2.0.3        clue_0.3-65           GetoptLong_1.0.5      matrixStats_1.3.0     compiler_4.4.1       
 [11] png_0.1-8             callr_3.7.6           vctrs_0.6.5           stringr_1.5.1         profvis_0.3.8        
 [16] pkgconfig_2.0.3       shape_1.4.6.1         crayon_1.5.3          fastmap_1.2.0         ellipsis_0.3.2       
 [21] labeling_0.4.3        caTools_1.18.2        utf8_1.2.4            promises_1.3.0        ncdfFlow_2.50.0      
 [26] sessioninfo_1.2.2     graph_1.82.0          ps_1.7.7              purrr_1.0.2           zlibbioc_1.50.0      
 [31] cachem_1.1.0          flowWorkspace_4.16.0  IDPmisc_1.1.21        later_1.3.2           jpeg_0.1-10          
 [36] flowViz_1.68.0        parallel_4.4.1        cluster_2.1.6         R6_2.5.1              stringi_1.8.4        
 [41] RColorBrewer_1.1-3    car_3.1-2             pkgload_1.4.0         Rcpp_1.0.13           iterators_1.0.14     
 [46] usethis_3.0.0         IRanges_2.38.1        httpuv_1.6.15         tidyselect_1.2.1      rstudioapi_0.16.0    
 [51] abind_1.4-5           doParallel_1.0.17     gplots_3.1.3.1        codetools_0.2-20      miniUI_0.1.1.1       
 [56] curl_5.2.1            processx_3.8.4        pkgbuild_1.4.4        lattice_0.22-6        tibble_3.2.1         
 [61] Biobase_2.64.0        shiny_1.9.1           withr_3.0.1           desc_1.4.3            urlchecker_1.0.1     
 [66] polyclip_1.10-7       circlize_0.4.16       pillar_1.9.0          carData_3.0-5         KernSmooth_2.23-24   
 [71] foreach_1.5.2         stats4_4.4.1          generics_0.1.3        S4Vectors_0.42.1      ggplot2_3.5.1        
 [76] munsell_0.5.1         scales_1.3.0          gtools_3.9.5          xtable_1.8-4          PeacoQC_1.14.0       
 [81] glue_1.7.0            tools_4.4.1           interp_1.1-6          hexbin_1.28.3         data.table_1.15.4    
 [86] XML_3.99-0.17         fs_1.6.4              grid_4.4.1            RProtoBufLib_2.16.0   latticeExtra_0.6-30  
 [91] devtools_2.4.5        colorspace_2.1-1      cli_3.6.3             fansi_1.0.6           cytolib_2.16.0       
 [96] ComplexHeatmap_2.20.0 dplyr_1.1.4           Rgraphviz_2.48.0      gtable_0.3.5          digest_0.6.36        
[101] BiocGenerics_0.50.0   farver_2.1.2          rjson_0.2.21          htmlwidgets_1.6.4     memoise_2.0.1        
[106] htmltools_0.5.8.1     lifecycle_1.0.4       GlobalOptions_0.1.2   mime_0.12             MASS_7.3-61

**Comment by 00berst33** [comment]
Ok, it seems flowCut is the culprit here. When flowFun is loaded, try:

```
fs <- system.file("extdata", "raw_flowset.rds", package = "flowFun")
fs <- readRDS(fs)

ff <- fs[[1]]

flowCut::flowCut(ff, Plot = "All")
```

I expect it to fail. If so try `flowCut::flowCut(ff, Plot = "None")` as well. I expect it to fail as well but let me know if not. If it does, you will have to install XQuartz: https://www.xquartz.org/ which lets Mac users run cross-platform apps, to use flowCut. I think that Macs used to have the functionality XQuartz provides by default, but that's no longer the case in more recent versions. I'd generally be against having you install external stuff but it seems to be pretty widespread and has other uses. flowCut could also be omitted but I think it's worth it, it seems to be one of our best if not the best option for cytometry QC right now.

From what I understand, this is necessary because flowCut imports the package Cairo, so when you call flowCut it tries to load Cairo as well. Normally you don't need to worry about this kind of thing, but this is a problem because Cairo relies on XQuartz being downloaded for it to work on Mac. And because XQuartz is external software R can't find it and throws an error.

If you do install XQuartz restart your computer before trying again. Hopefully that fixes this issue...but if not let me know.

**Comment by rmorgan7e** [comment]
The first two things failed  so I installed XQuartz and restarted my computer. That mostly worked. I was able to run the pre-processing without errors. The only problem is that something went wrong with generating the PDF. The file is there but it is only 3.5Kb and won't open (either with Preview [the PDF viewer for Macs]) or with google chrome). Based on the file size I think something went wrong generating the PDF. I tried rerunning it, quitting and trying again but still no luck.
